apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 100
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: paulbouwer/hello-kubernetes:1.5
        ports:
          - containerPort: 80
        env:
          - name: "MESSAGE"
            value: "Hello from the first deployment!"